# This workflow will build a flutter application
name: Build PR Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: "17"
          distribution: "oracle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.x"

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Android
        run: flutter build apk
